### PR TITLE
test: ensure protected endpoints reject requests without Authorization header

### LINKED ISSUE #130: [Backend] Missing Authorization Header
Title: Ensure protected endpoints reject requests without Authorization header

🎯 What We Are Testing

All endpoints that require authentication must reject requests if no Authorization: Bearer <token> header is provided.

🚨 Why This Matters

If this fails, anyone could:

- Create plans

- Claim funds

- Approve KYC

- Access admin logs

Without being authenticated.

🧪 Test Scenarios

Send requests to:

- POST /api/plans

- POST /api/plans/:id/claim

- GET /api/plans/:id

- GET /api/notifications

- GET /api/admin/logs

Without Authorization header.

✅ Expected Result

- HTTP 401 Unauthorized

Clear error message

📁 Test File
```bash
/tests/security_tests.rs
```

### Implementation Requirement

All tests must be written as integration tests inside the `/tests` directory using `#[tokio::test]`.

Tests must use the actual Axum router (via `create_app`) and not mock HTTP handlers directly.

### PR DESCRIPTION
**Pull request by MerlinTheWhiz**
Closes #130 

Changes I Made:
- Added integration tests in tests/security_tests.rs to verify protected endpoints return 401 Unauthorized when no Authorization: Bearer header is provided.
- Tested endpoints:
   - POST /api/plans
   - POST /api/plans/:id/claim
   - GET /api/plans/:id
   - GET /api/notifications
   - GET /api/admin/logs
- Tests use the real Axum router via create_app (no mocked handlers).
- All tests implemented as #[tokio::test] integration tests inside /tests.
- Added assertion to ensure response body includes {"error": "Unauthorized"}.
- Tests skip gracefully if DATABASE_URL is not set (consistent with existing patterns).

Screenshot of tests passed:

image

### CODE REVIEW

File: backend/tests/security_tests.rs [hunk 1]
```diff
@@ -0,0 +1,167 @@
+mod helpers;
```
Comment (ONEONUORA) [inline backend/tests/security_tests.rs]: @MerlinTheWhiz Pls change the file name from security_tests.rs to Auth_header.rs
